#!/bin/sh

id=`cat .next/BUILD_ID`
outdir="public"
jekyll=".nojekyll"

touch "$outdir/$jekyll" 
touch "$outdir/_next/static/$id/pages/$jekyll"
git add "$outdir/_next/static/" "$outdir/$jekyll"
git commit -am 'deploy'
git push origin master
git subtree push --prefix $outdir origin gh-pages
